### ISSUE TITLE
error: type_half.inl and Header Search Paths

### ISSUE THREAD

**Issue by furybubu** [dourgulf/VideoCore#1]
First of all, thanks a lot for the improvements you brought to Videocore.
After installing your version with cocoapods, I am having the typical error:type_half.inl that you said could be fixed after removing a few items in Header Search Paths.
Unfortunately,  these items are not there, These are the closest I have:
"${PODS_ROOT}/Headers/Public"
"${PODS_ROOT}/Headers/Public/VideoCore"
Removing these items had no effect whatsoever.

Any clue on how I could fix this?

**Comment by dourgulf** [comment]
About compile error after Pods:
1. fatal error: 'type_half.inl' file not found :
    a) select Pods project's in workspace, and select "VideoCore" target
    b) locate "Header Search Paths" setting items
    c) remove two item in this setting: ${PODS_ROOT}/Headers/Private" and "${PODS_ROOT}/Headers/Private/VideoCore"

Thanks for your report, I will update the README to help all users.

**Comment by furybubu** [comment]
It worked great, thanks! I also had to add Pods/VideoCore/api/iOS/** in User Header Search Paths of my target because it was complining about not finding VCSimpleSession.h

**Comment by dourgulf** [comment]
maybe you can use 
#import <videocore/api/iOS/VCSimpleSession.h>
coz this project almost writed by C++, it use C++'s include style.
